version: "3"

services:
  {{ APP_NAME }}:
    image: {{ APP_NAME }}:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - erlangms_{{ APP_NAME }}
    volumes:
      - "./app:/app"
    ports:
      - "{{ HTTP_PORT }}:{{ HTTP_PORT }}"
      - "{{ HTTPS_PORT }}:{{ HTTPS_PORT }}"

networks:
  erlangms_{{ APP_NAME }}:
